### PR TITLE
ensure response_count is used

### PR DESCRIPTION
**Pull request by ryanwoldatwork**
* instead of submissions.size, which queries the DB

### CODE REVIEW

**Review by aktfrikshun — COMMENTED** [review]
@ryanwoldatwork According to the documentation for counter_cache option on ActiveRecord, you do not have to reference response count directly.   

Simply using the access form.submissions.size will use the cached value.

In fact, you can call response_count anything and you won't have to update the entire code base wherever form.submissions.size is used.

**Comment by ryanwoldatwork** [comment]
thanks @aktfrikshun

I saw something like that as well, but the logs show a different story, so I went forth with these changes.

submission-queries

I think the specific issue is that the field needs to be named `submissions_count` in order for this to work.

**Comment by aktfrikshun** [comment]
I’d be curious to see if the query was actually hitting the db or if the SQL is being intercepted by the helper. 

The docs specifically say you can call the counter field anything you want so long as it is named in the belongs_to association.

But it probably makes no difference as we won’t be changing the name of the counter field.   It would just be nice if we could rely on the cache to work as expected if future developers reference the collection size method unaware.

Allen

**Comment by ryanwoldatwork** [comment]
I tested this locally using `submissions_count` and it seems to work, meaning the SQL query isn't called.

In the future, `response_count` could be renamed to `submissions_count`

**Pull request merged**
