### PR TITLE
update gems and form styling

### PR DESCRIPTION
**Pull request by ryanwoldatwork**

### CODE REVIEW

**Comment by ryanwoldatwork** [comment]
existing
this-branch

**Comment by ryanwoldatwork** [comment]
public-page-existing
public-page-this-branch

**Review by aktfrikshun — COMMENTED** [review]
Looking much better.

Not seeing any visible grouping of the section though.  Hard to tell where one section ends and another begins and it looks really weird when dragging a section to change the order.

Let me know if there are bits you want me to tackle on the UI cleanup.

Screen Shot 2021-01-22 at 10 02 56 AM

**Comment by ryanwoldatwork** [comment]
good note on the section backgrounds.
In preview, all sections are displayed on 1 page. In the public layout, each section is showed individually.

**Pull request merged**
