### PR TITLE
Compile widget after382

### PR DESCRIPTION
**Pull request by ryanwoldatwork**

### CODE REVIEW

**Review by sanason — COMMENTED** [review]
Should we also update the USWDS assets used by the Touchpoints app (run `npx gulp updateUswds`)?

**Comment by ryanwoldatwork** [comment]
ya, if there's a conventional way to run the tasks

**Comment by sanason** [comment]
`npx gulp updateUswds` updates the assets for the Touchpoints app.

https://github.com/GSA/touchpoints/wiki/Developer-Guide#updating-uswds

**Review by sanason — CHANGES_REQUESTED** [review]
I think it'll cause confusion if we don't update both the app and widget when we upgrade the USWDS version.

https://github.com/GSA/touchpoints/wiki/Developer-Guide#updating-uswds

**Comment by ryanwoldatwork** [comment]
I added a npm script `updateUswds` to run all the commands.

Doing so yielded the following diff.
But it looks like that can all be ignored. Thoughts?

fsddsfsdasfdfsa

**Review by sanason — APPROVED** [review]
👍

**Comment by sanason** [comment]
> Doing so yielded the following diff. But it looks like that can all be ignored. Thoughts?

Yes, agreed. In particular, I have a [USWDS PR](https://github.com/uswds/uswds/pull/6026) out to prevent the changes in `_widget-uswds.js.erb`.

**Pull request merged**
